"""add index on appointments barber_id

Revision ID: 0650842e6244
Revises: a30c2a9247f5
Create Date: 2026-06-08 16:37:59.311003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0650842e6244'
down_revision: Union[str, Sequence[str], None] = 'a30c2a9247f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_barber_id'), 'appointments', ['barber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_barber_id'), table_name='appointments')
    # ### end Alembic commands ###
