"""add rating column to barbers

Revision ID: a30c2a9247f5
Revises: 3ceb06657773
Create Date: 2026-06-08 16:25:06.605615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30c2a9247f5'
down_revision: Union[str, Sequence[str], None] = '3ceb06657773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barbers', 'rating')
    # ### end Alembic commands ###
